Feat/challenge 03 loops conditionals
Manel0712/Manel0712-JavaScript-foundations pull request #4
Opened 2023-10-31 18:54 UTC by Manel0712

2023-11-05 13:06 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +let number = 9;
⚠️ FIX: use 🇬🇧, please.

⚠️ FIX:  change the variable to test it works for different cases. 

⚠️ FIX: add a comment to print expected output.

2023-11-05 13:17 UTC, tictools requested changes

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_02.js
> +  The error is that the conditions only check that the age is greater than the number indicated, but not that they are less than the number indicated in the following condition.
How would you fix it?

⚠️ FIX: redefine script to fix the bug

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i = i + 2) {
Variables are always defined using camelCase convention, they never start by capital letter.
You should also take in account what they are storing.
⚠️ FIX: rename properly for variables in both cases

These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.
⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 0; i <= 10; i++) {
⚠️ FIX: rename properly for variables

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
This is the output of your script
```
'Half way there'

'You made it!'

'Checkpoint! 10'
'Checkpoint! 20'
'Checkpoint! 30'
'Checkpoint! 40'
'¡All, done!'
'Checkpoint! 60'
'Checkpoint! 70'
'Checkpoint! 80'
'Checkpoint! 90'
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +let loggedln = false;
⚠️ FIX: rename properly variable `i`

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +let i = 10;
⚠️ FIX: rename properly variables `i` and `c`

These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.
⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-05 13:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +*/
This is the output of your script
```
'Half way there!'

'You made it!'

'Checkpoint! 10'
'Checkpoint! 20'
'Checkpoint! 30'
'Checkpoint! 40'
100
'All, done!'
'Checkpoint! 60'
'Checkpoint! 70'
'Checkpoint! 80'
'Checkpoint! 90'
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-11 14:34 UTC, Enma1920 approved these changes

2023-11-11 14:35 UTC, Enma1920 approved these changes

2023-11-11 15:00 UTC, tictools requested changes

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let evennumbers = 10; evennumbers <= 40; evennumbers++) {
@Manel0712  @Enma1920 
Pay atention! Variables are defined using camelCase convention
```suggestion
for (let evenNumbers = 10; evenNumbers <= 40; evenNumbers++) {
```

FIX: apply suggestion

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let oddnumbers = 10; oddnumbers <= 40; oddnumbers++) {
Also here. 

FIX: use camelCase convetion

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
FIX: name properly variables

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +  i % 10 === 0
It's not a good idea use ternaries nested inside ternaries. Avoid this kind of implementations, they can be so difficult to read.

FIX: take a look at soltuions and refactor ternary

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +let evennumbers = 10;
FIX: Also here.

FIX: use camelCase convetion in all cases

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +let i = 1;
FIX: name properly variables

2023-11-11 15:00 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +  i % 10 === 0
It's not a good idea use ternaries nested inside ternaries. Avoid this kind of implementations, they can be so difficult to read.

FIX: take a look at soltuions and refactor ternary

2023-11-12 11:44 UTC, Enma1920 approved these changes

2023-11-12 11:47 UTC, Enma1920 approved these changes

2023-11-12 13:09 UTC, tictools requested changes

2023-11-12 13:09 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +function readnumbers(number) {
CamelCase

2023-11-12 13:09 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +function readnumbers(number) {
CamelCase

2023-11-12 14:57 UTC, Enma1920 approved these changes

2023-11-12 15:32 UTC, tictools approved these changes

2023-11-12 15:38 UTC, merged